language: go
go:
  - 1.7.4
install:
  - go get github.com/golang/crypto/blowfish
  - go get github.com/golang/crypto/cast5
  - go get github.com/golang/crypto/salsa20
  - go get github.com/Yawning/chacha20
  - go install ./cmd/shadowsocks-local
  - go install ./cmd/shadowsocks-server
script:
  - PATH=$PATH:$HOME/gopath/bin bash -x ./script/test.sh
sudo: false